
from arbol import Arbol

def main():
    myArbol = Arbol()
    myArbol.insertar(10)
    myArbol.insertar(5)
    myArbol.insertar(12)
    myArbol.insertar(4)
    myArbol.insertar(7)
    myArbol.insertar(3)
    myArbol.insertar(6)
    myArbol.insertar(9)
    myArbol.insertar(8)
    myArbol.insertar(11)
    myArbol.insertar(14)
    myArbol.insertar(13)
    myArbol.insertar(2)
    myArbol.insertar(1)
    myArbol.insertar(15)
    myArbol.insertar(10)
    myArbol.insertar(17)
    myArbol.insertar(18)
    myArbol.insertar(16)
    print("Altura del arbol: {}".format(myArbol.AlturaArbol()))
    print("InOrden: ")
    myArbol.InOrden()
    print("")
    print("PreOrden: ")
    myArbol.PreOrden()
    print("")
    print("PostOrden: ")
    myArbol.PostOrden()
    print("")
    print("Numero de nodos: {}".format(myArbol.NumeroNodos()))
    myArbol.borrar(5)
    print("Borrar 5")
    myArbol.InOrden()
    print("")
    myArbol.borrar(8)
    print("Borrar 8")
    myArbol.InOrden()
    print("")
    myArbol.borrar(15)
    print("Borrar 15")
    myArbol.InOrden()
    print("")
    myArbol.borrar(245)
    print("Borrar 245")
    myArbol.InOrden()
    print("")
    myArbol.borrar(4)
    print("Borrar 4")
    myArbol.InOrden()
    print("")
    myArbol.borrar(17)
    print("Borrar 17")
    myArbol.InOrden()
    print("")
    print("Numero de nodos: {}".format(myArbol.NumeroNodos()))
    print("Altura de 1: {}".format(myArbol.Altura(1)))
    print("Altura de 10: {}".format(myArbol.Altura(10)))
    print("Altura del arbol: {}".format(myArbol.AlturaArbol()))


if __name__ == '__main__':
    main()
